// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2EKrwK_SSwUNq0g5Ubb_hawaWcdBeL7o',
    appId: '1:690409335402:web:6533dc89016d72c3efb813',
    messagingSenderId: '690409335402',
    projectId: 'chientalk2025',
    authDomain: 'chientalk2025.firebaseapp.com',
    storageBucket: 'chientalk2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaWNPPcZg3Y19syo1UTVseMZ-CEEzFjqU',
    appId: '1:690409335402:ios:d9aed479411c6b15efb813',
    messagingSenderId: '690409335402',
    projectId: 'chientalk2025',
    storageBucket: 'chientalk2025.firebasestorage.app',
    iosBundleId: 'com.example.talktalk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaWNPPcZg3Y19syo1UTVseMZ-CEEzFjqU',
    appId: '1:690409335402:ios:d9aed479411c6b15efb813',
    messagingSenderId: '690409335402',
    projectId: 'chientalk2025',
    storageBucket: 'chientalk2025.firebasestorage.app',
    iosBundleId: 'com.example.talktalk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2EKrwK_SSwUNq0g5Ubb_hawaWcdBeL7o',
    appId: '1:690409335402:web:e2bfdb69c3be991befb813',
    messagingSenderId: '690409335402',
    projectId: 'chientalk2025',
    authDomain: 'chientalk2025.firebaseapp.com',
    storageBucket: 'chientalk2025.firebasestorage.app',
  );
}
